STYLES = {
    "light": (
        "QMainWindow, QWidget { background-color: #f5f5f5; color: #333; font-family: 'Segoe UI', sans-serif; }"
        "QListWidget { background-color: #ffffff; border: none; border-right: 1px solid #ddd; font-size: 16px; }"
        "QListWidget::item { padding: 15px; border-bottom: 1px solid #f0f0f0; }"
        "QListWidget::item:selected { background-color: #e3f2fd; color: #000; font-weight: bold; }"
        "QPushButton { background-color: #007bff; color: white; border-radius: 6px; padding: 10px; font-weight: bold; border: none; }"
        "QPushButton:hover { background-color: #0056b3; }"
        "QLineEdit, QTextEdit, QComboBox { background-color: white; border: 1px solid #ccc; border-radius: 6px; padding: 8px; color: #333; }"
        "QCalendarWidget QTableView { background-color: white; color: #333; selection-background-color: #007bff; selection-color: white; }"
        "QCalendarWidget QToolButton { color: #333; background-color: transparent; }"
        "QCalendarWidget QWidget#qt_calendar_navigationbar { background-color: #e0e0e0; }"
        "QTableWidget { background-color: white; gridline-color: #ddd; border: 1px solid #ddd; }"
        "QTableWidget::item:selected { background-color: #e3f2fd; color: #000; }"
        "QHeaderView::section { background-color: #f0f0f0; padding: 8px; font-weight: bold; border: 1px solid #ddd; }"
        "QGroupBox { font-weight: bold; border: 1px solid #ccc; border-radius: 6px; margin-top: 10px; padding-top: 10px; }"
        "QGroupBox::title { subcontrol-origin: margin; left: 10px; padding: 0 5px; }"
    ),
    "dark": (
        "QMainWindow, QWidget { background-color: #121212; color: #e0e0e0; font-family: 'Segoe UI', sans-serif; }"
        "QListWidget { background-color: #1e1e1e; border: none; border-right: 1px solid #333; font-size: 16px; }"
        "QListWidget::item { padding: 15px; border-bottom: 1px solid #2c2c2c; }"
        "QListWidget::item:selected { background-color: #3a7bd5; color: white; font-weight: bold; }"
        "QPushButton { background-color: #3a7bd5; color: white; border-radius: 6px; padding: 10px; font-weight: bold; border: none; }"
        "QPushButton:hover { background-color: #5a95e5; }"
        "QLineEdit, QTextEdit, QComboBox { background-color: #2d2d2d; border: 1px solid #444; border-radius: 6px; padding: 8px; color: white; }"
        "QCalendarWidget { background-color: #121212; }"
        "QCalendarWidget QTableView { background-color: #1e1e1e; color: #e0e0e0; selection-background-color: #3a7bd5; selection-color: white; gridline-color: #444; alternate-background-color: #252525; outline: 0px; }"
        "QCalendarWidget QTableView::item:selected { background-color: #3a7bd5; color: white; }"
        "QCalendarWidget QTableView::item:hover { background-color: #2a2a2a; }"
        "QCalendarWidget QToolButton { color: #e0e0e0; background-color: #252525; border: 1px solid #444; border-radius: 4px; margin: 2px; padding: 4px; font-weight: bold; }"
        "QCalendarWidget QToolButton:hover { background-color: #3a3a3a; }"
        "QCalendarWidget QToolButton::menu-indicator { image: none; }"
        "QCalendarWidget QWidget#qt_calendar_navigationbar { background-color: #252525; }"
        "QCalendarWidget QSpinBox { background-color: #2d2d2d; color: white; selection-color: white; selection-background-color: #3a7bd5; border: 1px solid #444; padding: 2px; border-radius: 4px; }"
        "QCalendarWidget QSpinBox::up-button, QCalendarWidget QSpinBox::down-button { background-color: #3a3a3a; border: none; width: 15px; }"
        "QCalendarWidget QSpinBox::up-button:hover, QCalendarWidget QSpinBox::down-button:hover { background-color: #4a4a4a; }"
        "QTableWidget { background-color: #1e1e1e; gridline-color: #444; border: 1px solid #444; color: #e0e0e0; }"
        "QTableWidget::item:selected { background-color: #3a7bd5; color: white; }"
        "QHeaderView::section { background-color: #2d2d2d; padding: 8px; font-weight: bold; border: 1px solid #444; color: #e0e0e0; }"
        "QGroupBox { font-weight: bold; border: 1px solid #444; border-radius: 6px; margin-top: 10px; padding-top: 10px; color: #e0e0e0; }"
        "QGroupBox::title { subcontrol-origin: margin; left: 10px; padding: 0 5px; }"
    )
}
